# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FindMyHospital' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'R.swift'
pod 'IQKeyboardManagerSwift'
pod 'FSCalendar'
pod 'SwiftyGif', '<= 4.2.0'
pod 'SwiftyJSON', '<= 4.2.0'
pod 'SwiftyJSONModel'
pod 'EzPopup'
pod 'Alamofire'
pod 'AMProgressHUD'
pod 'ReachabilitySwift'



end
